# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rgen.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nrgen.proto\x12\x04rgen\"3\n\x07Request\x12\x12\n\npatient_id\x18\x01 \x01(\t\x12\x14\n\x0clink_to_xray\x18\x02 \x01(\t\".\n\x08Response\x12\x12\n\npatient_id\x18\x01 \x01(\t\x12\x0e\n\x06report\x18\x02 \x01(\t27\n\x04RGen\x12/\n\x0eGenerateReport\x12\r.rgen.Request\x1a\x0e.rgen.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rgen_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=20
  _globals['_REQUEST']._serialized_end=71
  _globals['_RESPONSE']._serialized_start=73
  _globals['_RESPONSE']._serialized_end=119
  _globals['_RGEN']._serialized_start=121
  _globals['_RGEN']._serialized_end=176
# @@protoc_insertion_point(module_scope)
